<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPINHYDW0EEC" failures="1" tests="18" name="testngPackage.AppTest" time="0.038" errors="0" timestamp="2024-06-01T13:38:32 IST" skipped="0">
  <testcase classname="testngPackage.AppTest" name="additionTest" time="0.002"/>
  <testcase classname="testngPackage.AppTest" name="powerTest" time="0.002"/>
  <testcase classname="testngPackage.AppTest" name="sinTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="squareRootTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="additionTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="additionTest" time="0.002"/>
  <testcase classname="testngPackage.AppTest" name="isNegativeTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="additionTest" time="0.002">
    <failure message="Addition Result is not as Expected expected [-112.43299999999999] but found [-112.433]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Addition Result is not as Expected expected [-112.43299999999999] but found [-112.433]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEquals(Assert.java:728)
at testngPackage.AppTest.additionTest(AppTest.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- additionTest -->
  <testcase classname="testngPackage.AppTest" name="divisionTest" time="0.002"/>
  <testcase classname="testngPackage.AppTest" name="additionTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="additionTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="isPositiveTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="divisionTest" time="0.002"/>
  <testcase classname="testngPackage.AppTest" name="subtractionTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="divisionTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="tangetTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="divisionTest" time="0.001"/>
  <testcase classname="testngPackage.AppTest" name="cosTest" time="0.015"/>
</testsuite> <!-- testngPackage.AppTest -->
